markdown:   		rdiscount
pygments:   		true
permalink:  		/:year/:month/:title.html
exclude:  			[Gemfile, Gemfile.lock, stats.xml]
auto:       		true
pygments:  			true
rdiscount:
  extensions: 		[smart]
paginate: 			5
tag_title_prefix: 	"dailyOemer - Posts über "